-- ============================================================================
-- Migração: converter pesquisador.id e empregado.id (entidade Funcionario)
-- de sequence "pooled" (GenerationType.AUTO) para IDENTITY (GenerationType.IDENTITY)
--
-- Motivo: com GenerationType.AUTO, o Hibernate usava uma sequence com
-- allocationSize padrão de 50, reservando blocos de 50 IDs em memória a cada
-- nextval(). Reinícios da aplicação durante o desenvolvimento descartavam o
-- bloco não usado, causando saltos grandes entre IDs consecutivos. As demais
-- entidades do projeto já usam IDENTITY, que incrementa 1 a 1 direto no banco.
--
-- Esse script NÃO apaga dados; apenas troca a forma de geração do próximo ID
-- e sincroniza o contador com o maior ID já existente em cada tabela.
--
-- Como rodar (ambiente docker-compose local):
--   docker exec -i apesc-postgres psql -U admin -d apesc_db < migrations/2026-08-13_convert_pesquisador_funcionario_to_identity.sql
--
-- Ou via psql direto:
--   psql -h localhost -p 5434 -U admin -d apesc_db -f migrations/2026-08-13_convert_pesquisador_funcionario_to_identity.sql
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- Tabela: pesquisador
-- --------------------------------------------------------------------------

-- Remove o default atual (nextval da sequence antiga usada pelo GenerationType.AUTO)
ALTER TABLE pesquisador ALTER COLUMN id DROP DEFAULT;

-- Converte a coluna para IDENTITY (cria e associa uma sequence interna nova,
-- de propriedade da coluna, incrementando 1 a 1)
ALTER TABLE pesquisador ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

-- Sincroniza o próximo valor da nova sequence com os dados já existentes,
-- evitando colisão de chave primária no próximo insert
SELECT setval(
    pg_get_serial_sequence('pesquisador', 'id'),
    COALESCE((SELECT MAX(id) FROM pesquisador), 0) + 1,
    false
);

-- Remove a sequence antiga (pooled) que o Hibernate criou para o AUTO, se existir
DROP SEQUENCE IF EXISTS pesquisador_seq;

-- --------------------------------------------------------------------------
-- Tabela: empregado (entidade Funcionario -> @Table(name = "empregado"))
-- --------------------------------------------------------------------------

ALTER TABLE empregado ALTER COLUMN id DROP DEFAULT;

ALTER TABLE empregado ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('empregado', 'id'),
    COALESCE((SELECT MAX(id) FROM empregado), 0) + 1,
    false
);

DROP SEQUENCE IF EXISTS empregado_seq;
DROP SEQUENCE IF EXISTS funcionario_seq;

COMMIT;

-- ============================================================================
-- Verificação pós-migração (opcional, rode manualmente):
--
-- SELECT column_name, column_default, is_identity, identity_generation
-- FROM information_schema.columns
-- WHERE table_name IN ('pesquisador', 'empregado') AND column_name = 'id';
--
-- Esperado: is_identity = 'YES', identity_generation = 'BY DEFAULT'
-- ============================================================================
