-- ============================================================================
-- Migração: cria as tabelas restantes do diagrama (permissoes, acervo_iconografico
-- + assuntos, acervo_documental_tombo/processos, biblioteca_livros_periodicos,
-- biblioteca_apoio), liga empregado.permissoes_id, e estende registro_consulta_item
-- para suportar os 6 tipos de acervo (antes só documental/cartográfico).
--
-- Como rodar (ambiente docker-compose local):
--   docker cp migrations/2026-08-18_cria_tabelas_restantes_e_estende_registro_consulta_item.sql apesc-postgres:/tmp/migracao.sql
--   docker exec -i apesc-postgres psql -U admin -d apesc_db -f /tmp/migracao.sql
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- 1. Tabelas simples (lookup/catálogo)
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS permissoes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_regra VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS acervo_iconografico_assuntos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assuntos VARCHAR(255)
);

-- --------------------------------------------------------------------------
-- 2. Liga empregado -> permissoes (opcional, sem dado a migrar)
-- --------------------------------------------------------------------------
ALTER TABLE empregado ADD COLUMN IF NOT EXISTS permissoes_id BIGINT REFERENCES permissoes(id);

-- --------------------------------------------------------------------------
-- 3. Tabelas de acervo restantes
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS acervo_documental_tombo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acervo_documental_id BIGINT NOT NULL REFERENCES acervo_documental(id),
    numero_tombo INTEGER
);

CREATE TABLE IF NOT EXISTS acervo_documental_processos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    acervo_documental_id BIGINT NOT NULL REFERENCES acervo_documental(id),
    caixa_identificacao VARCHAR(255),
    localizacao VARCHAR(255),
    nome_processo VARCHAR(255),
    data VARCHAR(255),
    identificacao_pasta VARCHAR(255),
    disponibilidade BOOLEAN
);

CREATE TABLE IF NOT EXISTS acervo_iconografico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento_id BIGINT NOT NULL REFERENCES tipo_documento(id),
    codigo_identificacao VARCHAR(255),
    titulo VARCHAR(255),
    localizacao VARCHAR(255),
    disponibilidade BOOLEAN,
    assunto_id BIGINT NOT NULL REFERENCES acervo_iconografico_assuntos(id)
);

CREATE TABLE IF NOT EXISTS biblioteca_livros_periodicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento_id BIGINT NOT NULL REFERENCES tipo_documento(id),
    titulo VARCHAR(255),
    subtitulo VARCHAR(255),
    autores VARCHAR(255),
    editora VARCHAR(255),
    edicao VARCHAR(255),
    ano VARCHAR(255),
    quantidade_exemplar INTEGER,
    classificacao VARCHAR(255),
    localizacao VARCHAR(255),
    disponibilidade BOOLEAN
);

CREATE TABLE IF NOT EXISTS biblioteca_apoio (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento_id BIGINT NOT NULL REFERENCES tipo_documento(id),
    orgao_produtor_id BIGINT NOT NULL REFERENCES entidade_produtora(id),
    titulo VARCHAR(255),
    periodo VARCHAR(255),
    quantidade_volume INTEGER,
    identificador VARCHAR(255),
    localizacao VARCHAR(255),
    disponibilidade BOOLEAN
);

-- --------------------------------------------------------------------------
-- 4. Estende registro_consulta_item de 2 pra 6 tipos de acervo
-- --------------------------------------------------------------------------
ALTER TABLE registro_consulta_item ADD COLUMN IF NOT EXISTS acervo_documental_processos_id BIGINT REFERENCES acervo_documental_processos(id);
ALTER TABLE registro_consulta_item ADD COLUMN IF NOT EXISTS acervo_iconografico_id BIGINT REFERENCES acervo_iconografico(id);
ALTER TABLE registro_consulta_item ADD COLUMN IF NOT EXISTS biblioteca_livros_periodicos_id BIGINT REFERENCES biblioteca_livros_periodicos(id);
ALTER TABLE registro_consulta_item ADD COLUMN IF NOT EXISTS biblioteca_apoio_id BIGINT REFERENCES biblioteca_apoio(id);

-- troca as constraints antigas (pensadas pra 2 tipos) pelas novas (6 tipos) —
-- nao ha dado a perder: as 7 linhas existentes so tem acervo_documental_id
-- preenchido, o que continua batendo com a nova regra (exatamente 1 de 6).
ALTER TABLE registro_consulta_item DROP CONSTRAINT IF EXISTS uk_registro_consulta_item_documental;
ALTER TABLE registro_consulta_item DROP CONSTRAINT IF EXISTS uk_registro_consulta_item_cartografico;
ALTER TABLE registro_consulta_item DROP CONSTRAINT IF EXISTS ck_registro_consulta_item_um_tipo;

ALTER TABLE registro_consulta_item ADD CONSTRAINT uk_rc_item_documental UNIQUE (registro_consulta_id, acervo_documental_id);
ALTER TABLE registro_consulta_item ADD CONSTRAINT uk_rc_item_documental_processos UNIQUE (registro_consulta_id, acervo_documental_processos_id);
ALTER TABLE registro_consulta_item ADD CONSTRAINT uk_rc_item_iconografico UNIQUE (registro_consulta_id, acervo_iconografico_id);
ALTER TABLE registro_consulta_item ADD CONSTRAINT uk_rc_item_cartografico UNIQUE (registro_consulta_id, acervo_cartografico_id);
ALTER TABLE registro_consulta_item ADD CONSTRAINT uk_rc_item_biblioteca_livros UNIQUE (registro_consulta_id, biblioteca_livros_periodicos_id);
ALTER TABLE registro_consulta_item ADD CONSTRAINT uk_rc_item_biblioteca_apoio UNIQUE (registro_consulta_id, biblioteca_apoio_id);

ALTER TABLE registro_consulta_item ADD CONSTRAINT ck_rc_item_um_tipo CHECK (
    (CASE WHEN acervo_documental_id IS NOT NULL THEN 1 ELSE 0 END) +
    (CASE WHEN acervo_documental_processos_id IS NOT NULL THEN 1 ELSE 0 END) +
    (CASE WHEN acervo_iconografico_id IS NOT NULL THEN 1 ELSE 0 END) +
    (CASE WHEN acervo_cartografico_id IS NOT NULL THEN 1 ELSE 0 END) +
    (CASE WHEN biblioteca_livros_periodicos_id IS NOT NULL THEN 1 ELSE 0 END) +
    (CASE WHEN biblioteca_apoio_id IS NOT NULL THEN 1 ELSE 0 END) = 1
);

COMMIT;

-- ============================================================================
-- Verificação pós-migração (opcional, rode manualmente):
--
-- \dt
-- \d registro_consulta_item
-- SELECT COUNT(*) FROM registro_consulta_item;  -- deve continuar 7
-- ============================================================================
