-- ============================================================================
-- Migração: consolida a tabela associativa por tipo (registro_consulta_acervo_documental)
-- numa tabela associativa única (registro_consulta_item), com uma FK nullable por
-- tipo de acervo (acervo_documental_id, acervo_cartografico_id — cada linha
-- preenche exatamente uma delas). Também cria acervo_cartografico, que ainda não
-- existia no banco.
--
-- Contexto: registro_consulta_acervo_documental era uma tabela associativa por
-- tipo (decisão anterior). Foi substituída por uma tabela associativa única com
-- múltiplas FKs, cada uma nullable, com CHECK garantindo exatamente 1 preenchida
-- por linha — ver RegistroConsultaItem.java.
--
-- Este script migra os dados existentes (1 linha antiga -> 1 linha nova, com
-- acervo_cartografico_id ficando NULL) e só depois remove a tabela antiga.
--
-- Como rodar (ambiente docker-compose local):
--   docker exec -i apesc-postgres psql -U admin -d apesc_db < migrations/2026-08-18_consolida_registro_consulta_item_e_acervo_cartografico.sql
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- 1. Cria acervo_cartografico (ainda não existia)
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS acervo_cartografico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_documento_id BIGINT NOT NULL REFERENCES tipo_documento(id),
    codigo_identificacao VARCHAR(255),
    titulo VARCHAR(255),
    dimensao VARCHAR(255),
    localizacao VARCHAR(255),
    localidade VARCHAR(255),
    quantidade_volume INTEGER,
    disponibilidade BOOLEAN
);

-- --------------------------------------------------------------------------
-- 2. Cria a tabela associativa única
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS registro_consulta_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_consulta_id BIGINT NOT NULL REFERENCES registro_consulta(id),
    acervo_documental_id BIGINT REFERENCES acervo_documental(id),
    acervo_cartografico_id BIGINT REFERENCES acervo_cartografico(id),
    quantidade INTEGER,
    periodo VARCHAR(255),
    CONSTRAINT uk_registro_consulta_item_documental UNIQUE (registro_consulta_id, acervo_documental_id),
    CONSTRAINT uk_registro_consulta_item_cartografico UNIQUE (registro_consulta_id, acervo_cartografico_id),
    CONSTRAINT ck_registro_consulta_item_um_tipo CHECK (
        (acervo_documental_id IS NOT NULL AND acervo_cartografico_id IS NULL)
        OR (acervo_documental_id IS NULL AND acervo_cartografico_id IS NOT NULL)
    )
);

-- --------------------------------------------------------------------------
-- 3. Migra os dados existentes de registro_consulta_acervo_documental
--    (só roda se a tabela antiga ainda existir — reexecução segura)
-- --------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.tables
        WHERE table_name = 'registro_consulta_acervo_documental'
    ) THEN
        INSERT INTO registro_consulta_item (registro_consulta_id, acervo_documental_id, quantidade, periodo)
        SELECT registro_consulta_id, acervo_documental_id, quantidade, periodo
        FROM registro_consulta_acervo_documental
        ON CONFLICT ON CONSTRAINT uk_registro_consulta_item_documental DO NOTHING;
    END IF;
END $$;

-- --------------------------------------------------------------------------
-- 4. Remove a tabela antiga (substituída pela tabela única)
-- --------------------------------------------------------------------------
DROP TABLE IF EXISTS registro_consulta_acervo_documental;

COMMIT;

-- ============================================================================
-- Verificação pós-migração (opcional, rode manualmente):
--
-- SELECT COUNT(*) FROM registro_consulta_item;  -- deve bater com o total antigo
-- SELECT to_regclass('public.registro_consulta_acervo_documental');  -- deve ser NULL
-- SELECT to_regclass('public.acervo_cartografico');  -- nao deve ser NULL
-- ============================================================================
