-- ============================================================================
-- Migração: extrai acervo_documental_id/periodo/quantidade de registro_consulta
-- para uma tabela associativa própria (registro_consulta_acervo_documental).
--
-- Motivo: registro_consulta tinha uma FK direta pra acervo_documental (1
-- registro de consulta = 1 item consultado). Isso impedia registrar mais de
-- um acervo documental na mesma visita sem gambiarra (lista de IDs numa
-- coluna). Agora 1 registro_consulta pode ter N itens, cada um com sua
-- própria quantidade/período.
--
-- Esse script migra os dados existentes (1 linha de registro_consulta com
-- acervo preenchido -> 1 linha nova em registro_consulta_acervo_documental) e
-- só depois remove as colunas antigas. Não roda automaticamente: o
-- spring.jpa.hibernate.ddl-auto=update do projeto cria a tabela nova sozinho,
-- mas NÃO migra os dados nem remove as colunas antigas — isso precisa ser
-- feito manualmente com este script antes/depois do deploy da nova versão.
--
-- Como rodar (ambiente docker-compose local):
--   docker exec -i apesc-postgres psql -U admin -d apesc_db < migrations/2026-08-17_extrai_registro_consulta_acervo_documental.sql
--
-- Ou via psql direto:
--   psql -h localhost -p 5434 -U admin -d apesc_db -f migrations/2026-08-17_extrai_registro_consulta_acervo_documental.sql
-- ============================================================================

BEGIN;

-- --------------------------------------------------------------------------
-- 1. Cria a tabela associativa (idempotente — não falha se o Hibernate já
--    tiver criado ela sozinho num start anterior da aplicação)
-- --------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS registro_consulta_acervo_documental (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registro_consulta_id BIGINT NOT NULL REFERENCES registro_consulta(id),
    acervo_documental_id BIGINT NOT NULL REFERENCES acervo_documental(id),
    quantidade INTEGER,
    periodo VARCHAR(255),
    CONSTRAINT uk_registro_consulta_acervo_documental UNIQUE (registro_consulta_id, acervo_documental_id)
);

-- --------------------------------------------------------------------------
-- 2. Migra os dados existentes de registro_consulta para a tabela nova
--    (só roda se as colunas antigas ainda existirem — reexecução segura)
-- --------------------------------------------------------------------------
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns
        WHERE table_name = 'registro_consulta' AND column_name = 'acervo_documental_id'
    ) THEN
        INSERT INTO registro_consulta_acervo_documental (registro_consulta_id, acervo_documental_id, quantidade, periodo)
        SELECT id, acervo_documental_id, quantidade, periodo
        FROM registro_consulta
        WHERE acervo_documental_id IS NOT NULL
        ON CONFLICT ON CONSTRAINT uk_registro_consulta_acervo_documental DO NOTHING;
    END IF;
END $$;

-- --------------------------------------------------------------------------
-- 3. Remove as colunas antigas de registro_consulta
-- --------------------------------------------------------------------------
ALTER TABLE registro_consulta DROP COLUMN IF EXISTS acervo_documental_id;
ALTER TABLE registro_consulta DROP COLUMN IF EXISTS periodo;
ALTER TABLE registro_consulta DROP COLUMN IF EXISTS quantidade;

COMMIT;

-- ============================================================================
-- Verificação pós-migração (opcional, rode manualmente):
--
-- SELECT COUNT(*) FROM registro_consulta_acervo_documental;
-- SELECT column_name FROM information_schema.columns WHERE table_name = 'registro_consulta';
--   -> não deve mais listar acervo_documental_id, periodo ou quantidade
-- ============================================================================
