package com.example.apesc.exception;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum ErrorConstants {

    DUPLICATE_NAME("Nome duplicado"),
    DUPLICATE_ABREVIACAO("Abreviação duplicada"),
    EMPTY_NAME("O nome não pode ser vazio"),
    EMPTY_ABREVIACAO("A abreviação não pode ser vazia"),
    INVALID_NAME("Nome do tipo de documento inválido"),
    NAME_NOT_FOUND("Nome não encontrado"),
    ABREVIACAO_NOT_FOUND("Abreviação não encontrada"),
    INVALID_ID("ID inválido"),
    ID_NOT_FOUND("ID não encontrado"),
    TIPO_DOCUMENTO_HAS_DOCUMENTS("Tipo de documento possui documentos associados e não pode ser deletado"),
    TIPO_DOCUMENTO_REQUIRED("Tipo de documento é obrigatório"),
    TIPO_DOCUMENTO_NOT_FOUND("Tipo de documento não encontrado"),
    ENTIDADE_PRODUTORA_REQUIRED("Entidade produtora é obrigatória"),
    ENTIDADE_PRODUTORA_NOT_FOUND("Entidade produtora não encontrada"),
    NATUREZA_TRANSACAO_REQUIRED("Natureza da transação é obrigatória"),
    QUANTIDADE_INVALIDA("Quantidade deve ser maior que zero"),
    PERIODO_REQUIRED("Período é obrigatório"),
    ESTANTE_REQUIRED("Estante é obrigatória"),
    QUANTIDADE_REQUIRED("Quantidade é obrigatória"),
    DUPLICATE_ACERVO("Já existe um registro no acervo documental com o mesmo tipo de documento, entidade produtora, entidade receptora e natureza de transação"),
    SAME_ENTIDADE_ID("Entidade produtora e receptora não podem ter o mesmo ID"),
    ENTIDADE_RECEPTORA_REQUIRED("Entidade receptora é obrigatória para esta natureza de transação"),
    NATUREZA_TRANSACAO_INVALIDA("Natureza de transação inválida para entidade receptora informada"),
    NOME_REQUIRED("Nome é obrigatório"),
    NOME_INCOMPLETE("Nome deve conter nome e sobrenome"),
    DATA_NASCIMENTO_REQUIRED("Data de nascimento é obrigatória"),
    GENERO_REQUIRED("Gênero é obrigatório"),
    NUMERO_MATRICULA_REQUIRED("Número de matrícula é obrigatório"),
    MATRICULA_DUPLICADA("Número de matrícula já existe"),
    CARGO_REQUIRED("Cargo é obrigatório"),
    SETOR_REQUIRED("Setor é obrigatório"),
    EMAIL_REQUIRED("Email é obrigatório"),
    EMAIL_INVALID("Email inválido"),
    CPF_REQUIRED("CPF é obrigatório"),
    CPF_DUPLICADO("CPF já cadastrado"),
    NACIONALIDADE_REQUIRED("Nacionalidade é obrigatória"),
    NUMERO_TELEFONE_REQUIRED("Número de telefone é obrigatório"),
    LOGRADOURO_REQUIRED("Logradouro é obrigatório"),
    NUMERO_CASA_REQUIRED("Número da casa é obrigatório"),
    BAIRRO_REQUIRED("Bairro é obrigatório"),
    CIDADE_REQUIRED("Cidade é obrigatória"),
    ESTADO_REQUIRED("Estado é obrigatório"),
    CEP_REQUIRED("CEP é obrigatório"),
    NIVEL_EDUCACIONAL_REQUIRED("Nível educacional é obrigatório"),
    PROFISSAO_REQUIRED("Profissão é obrigatória"),
    ASSUNTO_PESQUISA_REQUIRED("Assunto da pesquisa é obrigatório"),
    FINALIDADE_PESQUISA_REQUIRED("Finalidade da pesquisa é obrigatória"),
    PERIODO_ESTUDO_REQUIRED("Período de estudo é obrigatório"),
    AREA_ESTUDO_REQUIRED("Área de estudo é obrigatória"),
    PESQUISADOR_HAS_REGISTRO_CONSULTA("Pesquisador possui registros de consulta associados e não pode ser deletado"),
    PESQUISADOR_REQUIRED("Pesquisador é obrigatório"),
    DATA_PESQUISA_REQUIRED("Data da pesquisa é obrigatória"),
    DATA_PESQUISA_INTERVALO_INCOMPLETO("Para buscar por intervalo, informe tanto a data inicial quanto a data final"),
    TIPO_CONSULTA_REQUIRED("Tipo de consulta é obrigatório"),
    FUNCIONARIO_REQUIRED("Funcionário é obrigatório"),
    REGISTRO_CONSULTA_DUPLICADO("Registro de consulta duplicado"),
    ITENS_REQUIRED("Pelo menos um item de acervo é obrigatório"),
    ACERVO_ITEM_REQUIRED("Cada item precisa referenciar um acervo (documental ou cartográfico)"),
    ACERVO_ITEM_TIPO_AMBIGUO("Um item não pode referenciar mais de um tipo de acervo ao mesmo tempo"),
    ACERVO_DOCUMENTAL_DUPLICADO_NO_REGISTRO("O mesmo acervo documental não pode aparecer mais de uma vez no mesmo registro de consulta"),
    ACERVO_CARTOGRAFICO_DUPLICADO_NO_REGISTRO("O mesmo acervo cartográfico não pode aparecer mais de uma vez no mesmo registro de consulta"),
    CODIGO_IDENTIFICACAO_REQUIRED("Código de identificação é obrigatório"),
    CODIGO_IDENTIFICACAO_DUPLICADO("Código de identificação já cadastrado"),
    TITULO_REQUIRED("Título é obrigatório"),
    DIMENSAO_REQUIRED("Dimensão é obrigatória"),
    LOCALIZACAO_REQUIRED("Localização é obrigatória"),
    LOCALIDADE_REQUIRED("Localidade é obrigatória"),
    DISPONIBILIDADE_REQUIRED("Disponibilidade é obrigatória"),
    NOME_REGRA_REQUIRED("Nome da regra é obrigatório"),
    NOME_REGRA_DUPLICADA("Nome da regra já cadastrado"),
    ASSUNTO_REQUIRED("Assunto é obrigatório"),
    ASSUNTO_DUPLICADO("Assunto já cadastrado"),
    ACERVO_DOCUMENTAL_REQUIRED("Acervo documental é obrigatório"),
    ACERVO_DOCUMENTAL_NOT_FOUND("Acervo documental não encontrado"),
    NUMERO_TOMBO_REQUIRED("Número de tombo é obrigatório"),
    NUMERO_TOMBO_DUPLICADO("Número de tombo já cadastrado para este acervo documental"),
    CAIXA_IDENTIFICACAO_REQUIRED("Caixa de identificação é obrigatória"),
    NOME_PROCESSO_REQUIRED("Nome do processo é obrigatório"),
    IDENTIFICACAO_PASTA_REQUIRED("Identificação da pasta é obrigatória"),
    PROCESSO_DUPLICADO("Já existe um processo com esta caixa de identificação para este acervo documental"),
    ASSUNTO_ICONOGRAFICO_REQUIRED("Assunto do acervo iconográfico é obrigatório"),
    ASSUNTO_ICONOGRAFICO_NOT_FOUND("Assunto do acervo iconográfico não encontrado"),
    AUTORES_REQUIRED("Autores é obrigatório"),
    EDITORA_REQUIRED("Editora é obrigatória"),
    ANO_REQUIRED("Ano é obrigatório"),
    ACERVO_DOCUMENTAL_PROCESSOS_DUPLICADO_NO_REGISTRO("O mesmo processo documental não pode aparecer mais de uma vez no mesmo registro de consulta"),
    ACERVO_ICONOGRAFICO_DUPLICADO_NO_REGISTRO("O mesmo acervo iconográfico não pode aparecer mais de uma vez no mesmo registro de consulta"),
    BIBLIOTECA_LIVROS_PERIODICOS_DUPLICADO_NO_REGISTRO("O mesmo item da biblioteca de livros/periódicos não pode aparecer mais de uma vez no mesmo registro de consulta"),
    BIBLIOTECA_APOIO_DUPLICADO_NO_REGISTRO("O mesmo item da biblioteca de apoio não pode aparecer mais de uma vez no mesmo registro de consulta");

    private final String description;

}
