package com.example.apesc.model.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum Nationality {
    BRAZILIAN("Brazilian"),
    AFGHAN("Afghan"),
    SOUTH_AFRICAN("South African"),
    ALBANIAN("Albanian"),
    GERMAN("German"),
    ANDORRAN("Andorran"),
    ANGOLAN("Angolan"),
    ANGUILLIAN("Anguillian"),
    ANTIGUAN("Antiguan"),
    NETHERLANDS_ANTILLEAN("Netherlands Antillean"),
    SAUDI_ARABIAN("Saudi Arabian"),
    ALGERIAN("Algerian"),
    ARGENTINE("Argentine"),
    ARMENIAN("Armenian"),
    ARUBAN("Aruban"),
    AUSTRALIAN("Australian"),
    AUSTRIAN("Austrian"),
    AZERBAIJANI("Azerbaijani"),
    BAHAMIAN("Bahamian"),
    BAHRAINI("Bahraini"),
    BANGLADESHI("Bangladeshi"),
    BARBADIAN("Barbadian"),
    BELGIAN("Belgian"),
    BELIZEAN("Belizean"),
    BENINESE("Beninese"),
    BERMUDIAN("Bermudian"),
    BELARUSIAN("Belarusian"),
    BOLIVIAN("Bolivian"),
    BOSNIAN("Bosnian"),
    BOTSWANAN("Botswanan"),
    BRUNEIAN("Bruneian"),
    BULGARIAN("Bulgarian"),
    BURKINABE("Burkinabé"),
    BURUNDIAN("Burundian"),
    BHUTANESE("Bhutanese"),
    CAPE_VERDEAN("Cape Verdean"),
    CAMEROONIAN("Cameroonian"),
    CANADIAN("Canadian"),
    CHADIAN("Chadian"),
    CHILEAN("Chilean"),
    CHINESE("Chinese"),
    COLOMBIAN("Colombian"),
    NORTH_KOREAN("North Korean"),
    IVORIAN("Ivorian"),
    COSTA_RICAN("Costa Rican"),
    CROATIAN("Croatian"),
    CUBAN("Cuban"),
    DANISH("Danish"),
    DJIBOUTIAN("Djiboutian"),
    DOMINICAN("Dominican"),
    EGYPTIAN("Egyptian"),
    SALVADORAN("Salvadoran"),
    EMIRATI("Emirati"),
    ECUADORIAN("Ecuadorian"),
    ERITREAN("Eritrean"),
    SCOTTISH("Scottish"),
    SLOVAK("Slovak"),
    SLOVENIAN("Slovenian"),
    SPANISH("Spanish"),
    MICRONESIAN("Micronesian"),
    AMERICAN("American"),
    ESTONIAN("Estonian"),
    ETHIOPIAN("Ethiopian"),
    FIJIAN("Fijian"),
    FILIPINO("Filipino"),
    FINNISH("Finnish"),
    FRENCH("French"),
    GABONESE("Gabonese"),
    GAMBIAN("Gambian"),
    GHANAIAN("Ghanaian"),
    GEORGIAN("Georgian"),
    GRENADIAN("Grenadian"),
    GREEK("Greek"),
    GUADELOUPEAN("Guadeloupean"),
    GUAMANIAN("Guamanian"),
    GUATEMALAN("Guatemalan"),
    GUYANESE("Guyanese"),
    FRENCH_GUIANESE("French Guianese"),
    GUINEAN("Guinean"),
    EQUATORIAL_GUINEAN("Equatorial Guinean"),
    BISSAU_GUINEAN("Bissau-Guinean"),
    HAITIAN("Haitian"),
    HONDURAN("Honduran"),
    HONG_KONGER("Hong Konger"),
    HUNGARIAN("Hungarian"),
    YEMENI("Yemeni"),
    FAROESE("Faroese"),
    SOLOMON_ISLANDER("Solomon Islander"),
    VIRGIN_ISLANDER("Virgin Islander"),
    INDIAN("Indian"),
    INDONESIAN("Indonesian"),
    ENGLISH("English"),
    IRANIAN("Iranian"),
    IRAQI("Iraqi"),
    IRISH("Irish"),
    NORTHERN_IRISH("Northern Irish"),
    ICELANDIC("Icelandic"),
    ISRAELI("Israeli"),
    ITALIAN("Italian"),
    JAMAICAN("Jamaican"),
    JAPANESE("Japanese"),
    JORDANIAN("Jordanian"),
    KOSOVAR("Kosovar"),
    LAO("Lao"),
    LESOTHO("Lesotho"),
    LATVIAN("Latvian"),
    LEBANESE("Lebanese"),
    LIBERIAN("Liberian"),
    LIBYAN("Libyan"),
    LIECHTENSTEINER("Liechtensteiner"),
    LITHUANIAN("Lithuanian"),
    LUXEMBOURGER("Luxembourger"),
    MACANESE("Macanese"),
    MACEDONIAN("Macedonian"),
    MALAGASY("Malagasy"),
    MALAYSIAN("Malaysian"),
    MALAWIAN("Malawian"),
    MALDIVIAN("Maldivian"),
    MALIEN("Malien"),
    MALTESE("Maltese"),
    MOROCCAN("Moroccan"),
    MARTINICAN("Martinican"),
    MAURITIAN("Mauritian"),
    MAURITANIAN("Mauritanian"),
    MEXICAN("Mexican"),
    MYANMAR("Myanmar"),
    MOZAMBICAN("Mozambican"),
    MOLDOVAN("Moldovan"),
    MONACAN("Monacan"),
    MONGOLIAN("Mongolian"),
    MONTENEGRIN("Montenegrin"),
    MONTSERRATIAN("Montserratian"),
    NAMIBIAN("Namibian"),
    NAURUAN("Nauruan"),
    NEPALESE("Nepalese"),
    NICARAGUAN("Nicaraguan"),
    NIGERIEN("Nigerien"),
    NIGERIAN("Nigerian"),
    NORWEGIAN("Norwegian"),
    NEW_CALEDONIAN("New Caledonian"),
    NEW_ZEALANDER("New Zealander"),
    OMANI("Omani"),
    WELSH("Welsh"),
    DUTCH("Dutch"),
    PALAUAN("Palauan"),
    PALESTINIAN("Palestinian"),
    PANAMANIAN("Panamanian"),
    PAPUA_NEW_GUINEAN("Papua New Guinean"),
    PAKISTANI("Pakistani"),
    PARAGUAYAN("Paraguayan"),
    PERUVIAN("Peruvian"),
    POLYNESIAN("Polynesian"),
    POLISH("Polish"),
    PUERTO_RICAN("Puerto Rican"),
    PORTUGUESE("Portuguese"),
    QATARI("Qatari"),
    KENYAN("Kenyan"),
    KYRGYZ("Kyrgyz"),
    BRITISH("British"),
    CZECH("Czech"),
    TAIWANESE("Taiwanese"),
    CONGOLESE("Congolese"),
    ROMANIAN("Romanian"),
    RWANDAN("Rwandan"),
    RUSSIAN("Russian"),
    SAINT_MARTINOIS("Saint-Martinois"),
    SAMOAN("Samoan"),
    SAINT_LUCIAN("Saint Lucian"),
    SAN_MARINESE("San Marinese"),
    SAO_TOMEAN("Sao Tomean"),
    SAINT_VINCENTIAN("Saint Vincentian"),
    SENEGALESE("Senegalese"),
    SIERRA_LEONEAN("Sierra Leonean"),
    SERBIAN("Serbian"),
    SEYCHELLOIS("Seychellois"),
    SINGAPOREAN("Singaporean"),
    SYRIAN("Syrian"),
    SOMALI("Somali"),
    SINHALESE("Sinhalese"),
    ESWATINI("Eswatini"),
    SUDANESE("Sudanese"),
    SWEDISH("Swedish"),
    SWISS("Swiss"),
    SURINAMESE("Surinamese"),
    TAJIK("Tajik"),
    THAI("Thai"),
    TANZANIAN("Tanzanian"),
    TIMORESE("Timorese"),
    TOGOLESE("Togolese"),
    TONGAN("Tongan"),
    TRINIDADIAN("Trinidadian"),
    TUNISIAN("Tunisian"),
    TURKS_AND_CAICOS_ISLANDER("Turks and Caicos Islander"),
    TURKMEN("Turkmen"),
    TURKISH("Turkish"),
    TUVALUAN("Tuvaluan"),
    UKRAINIAN("Ukrainian"),
    UGANDAN("Ugandan"),
    URUGUAYAN("Uruguayan"),
    UZBEK("Uzbek"),
    VANUATUAN("Vanuatuan"),
    VATICAN("Vatican"),
    VENEZUELAN("Venezuelan"),
    VIETNAMESE("Vietnamese"),
    ZAMBIAN("Zambian"),
    ZIMBABWEAN("Zimbabwean");

    private final String displayName;

}


